# k8s/api-ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: exosphere-landing-page-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`exosphere.host`)
      kind: Rule
      services:
        - name: exosphere-landing-page
          namespace: default
          port: 80
  tls:
    certResolver: letsencrypt